### ISSUE TITLE
Software requirements for developer machines

### ISSUE THREAD

**Issue by tgjones** [redbadger/XPF#3]
It would be useful to list the software requirements for developer machines in the readme, for those who wish to contribute. I haven't been able to get XPF.sln to build, on Windows 7 / 8, or Visual Studio 2010 / 2012. I assume it's because I don't have the right combination of Windows Phone SDKs, etc.

By the way, what is XPF.local.sln?

(Once I get the solution building, I plan to contribute a RedBadger.Xpf.Adapters.MonoGame adapter, which will simply link in the Xna adapter files and reference the MonoGame assembly.)

**Comment by jcdickinson** [comment]
Thanks for the interest tgjones, I'm a bit bunkered down with work and real life at the moment but will add this documentation as soon as possible.

In reality you shouldn't be having any issues with XNA dependencies unless you are trying to get the XNA adapter to work: if you have your machine set up for MonoGame flipping the references _should_ just work. The core XPF assembly has zero dependencies on XNA (although it does require Reactive Extensions, but nuget should automatically pull that down when you open the solution). Otherwise, you will need to get the full XNA game studio: http://www.microsoft.com/en-za/download/details.aspx?id=23714

In theory XPF.local.sln should automatically be excluded from commits; allowing you to add your own test projects to it.

**Comment by tgjones** [comment]
Thanks for the reply! I do have XNA Game Studio 4.0 installed, but that's not exactly the issue.

XPF.sln is a Visual Studio 2012 solution, but XNA Game Studio 4.0 projects aren't supported in VS2012. Well, they sort of are, but only if you have Windows Phone 8 SDK installed, and even then the only supported platform for XNA projects is Windows Phone.

If I open XPF.sln in Visual Studio 2010, none of the phone projects load - and somehow, some of the non-phone projects then fail to build (I haven't yet worked out why). Is there a particular version of the Windows Phone SDK that I need to install? Perhaps Windows Phone 7.1 SDK?

**Comment by jcdickinson** [comment]
I personally didn't do the final testing for XNA (codedjinn did), I merely made sure all the unit tests were passing. However, he did point me toward this StackOverflow question when we first got this repo going: http://stackoverflow.com/questions/10881005/how-to-install-xna-game-studio-on-visual-studio-2012

I'll ping him quickly and nag him to help you out here.

**Comment by codedjinn** [comment]
So the link Jono provided will do the trick.  You just have to copy the XNA project templates from VS 2010 to VS 2012 (to the right locations of course).  That also said, compiling the adapter for mono is exactly as easy as Jono said, you basically just change the XNA dlls to the MonoGame dll, and it will work as I have done this myself.

Please don't hesitate to ask anything else.

Regards,
Jaco
